[package]
name = "link-budget-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { path = "../egui/crates/eframe", features = [] }
egui = {path = "../egui/crates/egui"}
egui_extras = {path = "../egui/crates/egui_extras"}
number_prefix = "0.4.0"
mundy = { version = "0.1.2" }